import type { Metadata } from "next";

import "./globals.css";
import localFont from "next/font/local";
import Footer from "@/components/Footer";
import Navbar from "@/components/navbar/Navbar";
import Contect from "@/components/Contect";


const munchiesFont = localFont({
  src: [
    {
      path: "./fonts/Munchies-Light.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/Munchies-Semibold.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Munchies-Bold.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-munchies",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${munchiesFont.variable} font-munchies antialiased  bg-[#fff7e8] pt-14 `}
      >
        <Navbar />
        {children}
        
        <Contect/>
        <Footer />
      </body>
    </html>
  );
}
